process CONCATENATE_CLUSTERS {

    conda params.stats_env

    publishDir "${params.outDir}/results/src/", 
        mode: 'copy',
        overwrite: true

    input:
        path(clusters)
        path(sequencing_summary, stageAs: "sequencing_summary.csv")

    output:
        path("unprocessed_clusters.tsv"),   emit: pairwise_clusters_unprocessed
        path("processed_clusters.tsv"),     emit: pairwise_clusters_processed

    script:

    """
    #!/usr/bin/env python
    import polars as pl
    from pathlib import Path

    base_dir = Path("${params.outDir}/db/comparison/mtbseq/")

    # ------------------------------------------------------------------
    # Find files
    # ------------------------------------------------------------------
    cluster_files = list(base_dir.rglob("${params.runID}*_d*.processed.clusters.tsv"))
    singleton_files = list(base_dir.rglob("${params.runID}*_d*.singletons.tsv"))
    all_files = cluster_files + singleton_files

    # ------------------------------------------------------------------
    # Read + combine
    # ------------------------------------------------------------------
    df0 = pl.concat([
        pl.read_csv(f, separator="\t", has_header=False)
        for f in all_files
    ])

    # Remove duplicates early
    df1 = df0.unique()

    # ------------------------------------------------------------------
    # Process cluster ID column (V4)
    # ------------------------------------------------------------------
    df2 = (
        df1
        .with_columns(
            pl.col("column_4")
            .str.split_exact("-", 2)
            .struct.rename_fields(["num", "dist", "lin"])
            .alias("parts")
        )
        .unnest("parts")
        .with_columns([
            pl.col("num").str.zfill(3),
            pl.col("dist").str.zfill(2)
        ])
        .with_columns(
            (pl.col("num") + "-" + pl.col("dist") + "-" + pl.col("lin"))
            .alias("column_4")
        )
        .select(["column_1", "column_2", "column_3", "column_4"])
    )

    # Rename columns
    df3 = df2.rename({
        "column_1": "lineage",
        "column_2": "dSNP",
        "column_3": "genomes",
        "column_4": "int_clusterID"
    })

    # Replace dist_ → t=
    df4 = df3.with_columns(
        pl.col("dSNP").str.replace("dist_", "t=")
    )
    
    df4 = df4.with_columns(pl.all().str.strip_chars())

    # ------------------------------------------------------------------
    # Create sample index to match MTBseq output name (removed libraryID) with the SampleID
    # ------------------------------------------------------------------
    # read sequencing summary
    database_sample_index = (
        pl.read_csv("sequencing_summary.csv", has_header=True)
        .select("Sample")
        .unique()
        .with_columns(
            pl.col("Sample")
            .str.split_exact("_", 1)
            .struct.rename_fields(["genomes", "library"])
            .alias("parts")
        )
        .unnest("parts")
        )

    # ------------------------------------------------------------------
    # Join + pivot
    # ------------------------------------------------------------------
    # Join the index with the df
    df_merged = database_sample_index.join(df4, on="genomes", how="left")

    ##database_sample_index.select("Sample").unique().count()
    ##df.select("Sample").unique().count()
    ##df_merged.select("Sample").unique().count()
    ##df_merged.filter(pl.col("lineage").is_null())

    # Pivot wider
    wide = df_merged.pivot(
        index=["SampleID", "lineage", "genomes", "library"],
        columns="dSNP",
        values="int_clusterID"
    )

    # ------------------------------------------------------------------
    # Sort t= columns numerically
    # ------------------------------------------------------------------
    t_cols = [c for c in wide.columns if c.startswith("t=")]
    t_cols_sorted = sorted(t_cols, key=lambda x: int(x.replace("t=", "")))

    wide = wide.select(["SampleID", "lineage"] + t_cols_sorted)

    # ------------------------------------------------------------------
    # Create merged cluster ID
    # ------------------------------------------------------------------
    wide = wide.with_columns(
        pl.concat_str(t_cols_sorted, separator="/")
        .alias("merged_clusterID")
    )

    # ------------------------------------------------------------------
    # Write outputs
    # ------------------------------------------------------------------
    wide.write_csv("processed_clusters.tsv", separator="\t")

    df.write_csv(
        "unprocessed_clusters.tsv",
        separator="\t",
        include_header=False
    )
    """
}

/*
    @author: Poppy J Hesketh Best
    @date: 2025-04-01
    @version: 2.0.0
    @description:
        This process concatenates all the cluster files generated by the pairwise analysis
        into a single file. The output is a tab-separated file with the following columns:
            - lineage
            - distance
            - genomes
            - group
        The output file is named "unprocessed_clusters.tsv".
    @changelog
        v1.0.0-2025-04-01: Initial version
        v1.0.1-2025-04-04: Added comprehensive error handling and debugging information
        v2.0.0-2025-12-03: Improved package installation and loading with error handling, 
                            added detailed input checks and logging
                        Moved from running a seperate Rscript to embedding the Rcode directly
                            into the nextflow module.
*/
