process CONCATENATE_CLUSTERS {

    conda params.stats_env

    publishDir "${params.outDir}/results/src/", 
        mode: 'copy',
        overwrite: true

    input:
        path(clusters)
        path(sequencing_summary, stageAs: "sequencing_summary.csv")

    output:
        path("unprocessed_clusters.tsv"),   emit: pairwise_clusters_unprocessed
        path("processed_clusters.tsv"),     emit: pairwise_clusters_processed

    script:

"""
import polars as pl
from pathlib import Path

base_dir = Path("${params.outDir}/db/comparison/mtbseq/")

# ------------------------------------------------------------------
# Find files
# ------------------------------------------------------------------
cluster_files = list(base_dir.rglob("*_d*.processed.clusters.tsv"))
singleton_files = list(base_dir.rglob("*_d*.singletons.tsv"))
all_files = cluster_files + singleton_files

# ------------------------------------------------------------------
# Read + combine
# ------------------------------------------------------------------
df = pl.concat([
    pl.read_csv(f, separator="\t", has_header=False)
    for f in all_files
])

# Remove duplicates early
df = df.unique()

# ------------------------------------------------------------------
# Process cluster ID column (V4)
# ------------------------------------------------------------------
df = (
    df
    .with_columns(
        pl.col("column_4")
        .str.split_exact("-", 2)
        .struct.rename_fields(["num", "dist", "lin"])
        .alias("parts")
    )
    .unnest("parts")
    .with_columns([
        pl.col("num").str.zfill(3),
        pl.col("dist").str.zfill(2)
    ])
    .with_columns(
        (pl.col("num") + "-" + pl.col("dist") + "-" + pl.col("lin"))
        .alias("column_4")
    )
    .select(["column_1", "column_2", "column_3", "column_4"])
)

# Rename columns
df = df.rename({
    "column_1": "lineage",
    "column_2": "dSNP",
    "column_3": "genomes",
    "column_4": "int_clusterID"
})

# Replace dist_ → t=
df = df.with_columns(
    pl.col("dSNP").str.replace("dist_", "t=")
)

# ------------------------------------------------------------------
# Read sequencing summary
# ------------------------------------------------------------------
sample_df = (
    pl.read_csv("sequencing_summary.csv")
    .select("Sample")
    .with_columns(pl.col("Sample").alias("genomes"))
    .with_columns(
        pl.col("genomes")
        .str.split_exact("_", 1)
        .struct.rename_fields(["id", "library"])
        .alias("parts")
    )
    .unnest("parts")
    .select([
        pl.col("Sample").alias("SampleID"),
        pl.col("id").alias("genomes")
    ])
    .unique()
)

# ------------------------------------------------------------------
# Join + pivot
# ------------------------------------------------------------------
df = (
    df.join(sample_df, on="genomes", how="left")
    .select(["SampleID", "lineage", "dSNP", "int_clusterID"])
    .unique()
)

wide = df.pivot(
    index=["SampleID", "lineage"],
    columns="dSNP",
    values="int_clusterID"
)

# ------------------------------------------------------------------
# Sort t= columns numerically
# ------------------------------------------------------------------
t_cols = [c for c in wide.columns if c.startswith("t=")]
t_cols_sorted = sorted(t_cols, key=lambda x: int(x.replace("t=", "")))

wide = wide.select(["SampleID", "lineage"] + t_cols_sorted)

# ------------------------------------------------------------------
# Create merged cluster ID
# ------------------------------------------------------------------
wide = wide.with_columns(
    pl.concat_str(t_cols_sorted, separator="/")
    .alias("merged_clusterID")
)

# ------------------------------------------------------------------
# Write outputs
# ------------------------------------------------------------------
wide.write_csv("processed_clusters.tsv", separator="\t")

df.write_csv(
    "unprocessed_clusters.tsv",
    separator="\t",
    include_header=False
)
"""
}

/*
    @author: Poppy J Hesketh Best
    @date: 2025-04-01
    @version: 2.0.0
    @description:
        This process concatenates all the cluster files generated by the pairwise analysis
        into a single file. The output is a tab-separated file with the following columns:
            - lineage
            - distance
            - genomes
            - group
        The output file is named "unprocessed_clusters.tsv".
    @changelog
        v1.0.0-2025-04-01: Initial version
        v1.0.1-2025-04-04: Added comprehensive error handling and debugging information
        v2.0.0-2025-12-03: Improved package installation and loading with error handling, 
                            added detailed input checks and logging
                        Moved from running a seperate Rscript to embedding the Rcode directly
                            into the nextflow module.
*/
