process CONCATENATE_CLUSTERS {

/*
    @author: Poppy J Hesketh Best
    @date: 2025-04-01
    @version: 1.0
    @description:
        This process concatenates all the cluster files generated by the pairwise analysis
        into a single file. The output is a tab-separated file with the following columns:
            - lineage
            - distance
            - genomes
            - group
        The output file is named "unprocessed_clusters.tsv".
*/

    conda params.r_stats_env

    publishDir "${params.outDir}/db/results/main/", mode: 'copy'

    input:
        path(clusters)
        path(sequencing_summary, stageAs: "sequencing_summary.csv")

    output:
        path("unprocessed_clusters.tsv"),   emit: pairwise_clusters_unprocessed
        path("processed_clusters.tsv"),     emit: pairwise_clusters_processed

    script:

        """
        #!/usr/bin/env Rscript --vanilla

        #--------------------------------------------------------------------------#
        # Load packages
        #--------------------------------------------------------------------------#

        # Set a default CRAN mirror (avoids prompt)
            options(repos = c(CRAN = "https://cloud.r-project.org"))

        # List of packages
            packages <- c("tidyverse", "dplyr")

        # Identify missing packages
            missing_pkgs <- packages[!packages %in% installed.packages()[, "Package"]]

        # Install missing packages (non-interactive)
            if (length(missing_pkgs) > 0) {
            install.packages(missing_pkgs, dependencies = TRUE)
            }

        # Load all packages
            invisible(lapply(packages, library, character.only = TRUE))

        #--------------------------------------------------------------------------#
        # Import all the dataframes and merge
        #--------------------------------------------------------------------------#

        # Define base directory
            base_dir <- "${params.outDir}/db/comparative/mtbseq/"

        # List all cluster and singleton files
            cluster_files <- list.files(path = file.path(base_dir), 
                                        pattern = "_d.*\\.clusters\\.tsv\$", 
                                        recursive = TRUE, 
                                        full.names = TRUE
                                        )

            singleton_files <- list.files(path = file.path(base_dir), 
                                        pattern = "_d.*\\.singletons\\.tsv\$", 
                                        recursive = TRUE, 
                                        full.names = TRUE
                                        )

        # Combine all files into a single vector
            all_files <- c(cluster_files, singleton_files)

        # Read all files (no header)
            df_list <- lapply(all_files, function(f) read.table(f, 
                                                                sep = "\t", 
                                                                header = FALSE, 
                                                                stringsAsFactors = FALSE
                                                                )
                            )

        # Merge all into one data frame
            merged_df <- do.call(rbind, df_list) |> distinct()

        #--------------------------------------------------------------------------#
        # Wrangle the files
        #--------------------------------------------------------------------------#

            raw_clust = merged_df
            colnames(raw_clust) <- c("lineage", "dSNP", "genomes", "int_clusterID")

            raw_clust <- raw_clust |>
            mutate(dSNP = gsub("dist_", "t=", dSNP))

        # Process the sampleIDs
            sample_id_df <- read.delim("sequencing_summary.csv",
                                header = TRUE, sep = ",") |>
            select(Sample) |>
            mutate(genomes = Sample) |>
            separate_wider_delim(genomes, delim = "_",
                                names = c("genomes", "library"),
                                too_few = "align_end") |>
            select(SampleID = Sample, genomes)

        # Merge and pivot the data
            raw_clust <- left_join(raw_clust, sample_id_df) |>
            distinct() |>
            select(SampleID, lineage, dSNP, int_clusterID) |>
            pivot_wider(names_from = dSNP, values_from = int_clusterID)

        # Extract and sort t= column names numerically
            t_cols <- names(raw_clust)[grepl("^t=", names(raw_clust))]
            t_cols_sorted <- t_cols[order(as.numeric(gsub("t=", "", t_cols)))]

        # Reorder the full data frame
            raw_clust <- raw_clust |>
            select(SampleID, lineage, all_of(t_cols_sorted))

        # Create the merged clusterID
            raw_clust <- raw_clust |>
            unite("merged_clusterID", all_of(t_cols_sorted), sep = "/", remove = FALSE) |>
            select(SampleID, lineage, all_of(t_cols_sorted), merged_clusterID)

        #··············································································#
        # Export the dataframe
        #··············································································#
            write.table(raw_clust, "processed_clusters.tsv",
                        sep = "\t", 
                        row.names = FALSE, 
                        quote = FALSE
                        )

            write.table(merged_df, file = "unprocessed_clusters.tsv", 
                        sep = "\t", 
                        row.names = FALSE, 
                        col.names = FALSE, 
                        quote = FALSE
                        )
        """

}
