process CONCATENATE_CLUSTERS {

/*
    @author: Poppy J Hesketh Best
    @date: 2025-04-01
    @version: 1.0
    @description:
        This process concatenates all the cluster files generated by the pairwise analysis
        into a single file. The output is a tab-separated file with the following columns:
            - lineage
            - distance
            - genomes
            - group
        The output file is named "unprocessed_clusters.tsv".
*/

    publishDir "${params.outDir}/bbdd/results/main/", mode: 'copy'

    input:
        path(clusters)

    output:
        path("unprocessed_clusters.tsv"),          emit: bbdd_clusters

    script:

        """
        # Create a header
            echo "lineage\tdistance\tgenomes\tgroup" > unprocessed_clusters.tsv

        # Concatenate all files
            for file in ${params.outDir}/bbdd/mtbseq/pairwise/*/Groups/*clusters.tsv; do 
                cat \$file >> unprocessed_clusters.tsv
            done

        """

}